### ISSUE TITLE
Can't create class

### ISSUE THREAD

**Issue by gjm** [thunderer/Platenum#10]
I'm trying to create this enum;
```php
namespace App;

use Thunder\Platenum\Enum\AbstractConstantsEnum;

class Enum extends AbstractConstantsEnum
{
    private const FOO = 'foo';
    private const BAR = 'bar';
}
```

When I try to create an instance:
```php
$enum = Enum::FOO();
```

I get:
```
Thunder/Platenum/Exception/PlatenumException with message 'Enum `App/Enum` does not implement resolve() method.'
```

**Comment by thunderer** [comment]
@gjm thanks for reporting the issue, I just released new version `v0.2` out of the current master. The issue was already fixed, just not released.

**Comment by thunderer** [comment]
@gjm please let me know if everything is okay on your side. If you have more questions, I'd be happy to answer them. Thanks for using the library!

**Comment by gjm** [comment]
@thunderer yes version 0.2 fixes the issue. Closing the issue. Thanks!
