### ISSUE TITLE
Private methods cannot be final

### ISSUE THREAD

**Issue by bigfoot90** [thunderer/Platenum#25]
**Running on PHP 8** this warning is coming out
> Private methods cannot be final as they are never overridden by other classes in /home/bigfoot/Progetti/CreateYourDish/Web/vendor/thunderer/platenum/src/Enum/ConstantsEnumTrait.php on line 12

**Comment by thunderer** [comment]
@bigfoot90 thanks for reporting this issue. I fixed it in #26 and released `v0.3.2`. Let me know if you have any other questions. :)
